#!/usr/bin/env python3
"""Apply Section 4 notebook edits from notes/task-3-4-synthetic-data.md to code_v2.ipynb."""
from __future__ import annotations

import json
from pathlib import Path

def _repo_root() -> Path:
    try:
        return Path(__file__).resolve().parent.parent
    except NameError:
        return Path.cwd()


ROOT = _repo_root()
NB_PATH = ROOT / "code_v2.ipynb"

MARKER_T3 = "T3_CONFIG  = 'config/train_t3_best.py'"


def src_lines(code: str) -> list[str]:
    if not code.endswith("\n"):
        code = code + "\n"
    parts = code.split("\n")
    return [p + "\n" for p in parts[:-1]] + ([parts[-1]] if parts[-1] != "" else [])


CELL_SYN_PREP = """# ── §2.5 — Build Synthetic ROCStories Dataset ────────────────────────────────
# Mixes gpt-oss-120B synthetic stories with original ROCStories.
# PREREQ: synthetic_stories_gptoss120b.json must be in LOCAL_DIR
#         (generated by the separate Groq Colab notebook)
# Train: ~19.5M synthetic tokens + ~2.9M original = ~22.4M total
# Val:   ~0.5M original-only tokens (authentic PPL signal for prof's test set)
import os, subprocess
os.chdir(LOCAL_DIR)

SYNTHETIC_JSON = os.path.join(LOCAL_DIR, 'synthetic_stories_gptoss120b.json')
SYNTHETIC_TRAIN = 'data/rocstories_synthetic/train.bin'
SYNTHETIC_VAL   = 'data/rocstories_synthetic/val.bin'

if not os.path.exists(SYNTHETIC_JSON):
    print(f"⚠  {SYNTHETIC_JSON} not found.")
    print(f"   Generate it first using the Groq Colab notebook.")
    print(f"   Then re-run this cell.")
elif os.path.exists(SYNTHETIC_TRAIN) and os.path.exists(SYNTHETIC_VAL):
    import numpy as np
    train_tok = len(np.fromfile(SYNTHETIC_TRAIN, dtype=np.uint16))
    val_tok   = len(np.fromfile(SYNTHETIC_VAL,   dtype=np.uint16))
    print(f"✓ Synthetic dataset already built:")
    print(f"  train.bin: {train_tok/1e6:.2f}M tokens")
    print(f"  val.bin:   {val_tok/1e3:.0f}K tokens")
else:
    print("Building synthetic dataset...")
    result = subprocess.run(
        ['python', 'data/rocstories_synthetic/prepare.py',
         '--json_path', SYNTHETIC_JSON],
        capture_output=True, text=True, cwd=LOCAL_DIR
    )
    print(result.stdout)
    if result.returncode != 0:
        print("STDERR:", result.stderr)
    else:
        import numpy as np
        train_tok = len(np.fromfile(SYNTHETIC_TRAIN, dtype=np.uint16))
        val_tok   = len(np.fromfile(SYNTHETIC_VAL,   dtype=np.uint16))
        print(f"✓ Dataset ready: {train_tok/1e6:.2f}M train tokens | "
              f"{val_tok/1e3:.0f}K val tokens")
"""

CELL_T3_SYN = """# ── §3.1b — Task 3: Synthetic Retrain (gpt-oss-120B knowledge distillation) ─
# Full retrain from scratch on synthetic + original ROCStories mix.
# Architecture IDENTICAL to original T3 (7L/6H/384D = 31.8M, ≤32M).
# Expected: PPL ~20-22, Qwen quality dramatically better than original.
# Runs ~25 min on A100. Best ckpt saved to out-t3-synthetic/ckpt_best.pt
import os
os.chdir(LOCAL_DIR)

T3_SYN_CONFIG  = 'config/train_t3_synthetic.py'
T3_SYN_OUT_DIR = 'out-t3-synthetic'

ckpt_syn = os.path.join(T3_SYN_OUT_DIR, 'ckpt.pt')
init_syn  = 'resume' if os.path.exists(ckpt_syn) else 'scratch'

print("━"*62)
print("  ▶  Task 3 Synthetic Retrain  ·  31.8M  ·  gpt-oss-120B KD")
print("━"*62)
print(f"  Model    : All-Modern 31.8M  (RoPE + RMSNorm + SwiGLU + QK-Norm)")
print(f"  Dataset  : data/rocstories_synthetic/  (~22.4M tokens)")
print(f"  Config   : {T3_SYN_CONFIG}")
print(f"  Out dir  : {T3_SYN_OUT_DIR}")
print(f"  Init     : {init_syn}")
print(f"  Steps    : 12,000  (~9 passes over 22M corpus)")
print(f"  ETA      : ~25 min on A100")
print()

run_streaming(
    ['python', '-u', 'train.py', T3_SYN_CONFIG,
     f'--init_from={init_syn}',
     f'--out_dir={T3_SYN_OUT_DIR}'],
    label="Task 3 Synthetic Retrain  ·  31.8M  ·  gpt-oss-120B KD"
)
"""

CELL_COMPARE = """# ── §3.3 — Compare T3 Original vs T3 Synthetic ───────────────────────────────
# Decides which checkpoint to upload to HuggingFace.
# Rule: use synthetic if (a) PPL within 3 points AND (b) stories clearly better
#       otherwise keep original (PPL matters for 15 marks)
import os, math, torch, json, subprocess
os.chdir(LOCAL_DIR)

def _load_ppl(ckpt_path):
    if not os.path.exists(ckpt_path):
        return None, None
    ck = torch.load(ckpt_path, map_location='cpu', weights_only=False)
    try:
        ppl = math.exp(ck['best_val_loss'])
        step = ck['iter_num']
    except:
        ppl, step = None, None
    return ppl, step

orig_ckpt = 'out-t3-best/ckpt_best.pt'
syn_ckpt  = 'out-t3-synthetic/ckpt_best.pt'

ppl_orig, step_orig = _load_ppl(orig_ckpt)
ppl_syn,  step_syn  = _load_ppl(syn_ckpt)

print("── T3 Checkpoint Comparison ─────────────────────────────────")
print(f"  Original   (out-t3-best):      step {step_orig}  PPL {ppl_orig:.2f}" if ppl_orig else "  Original: not found")
print(f"  Synthetic  (out-t3-synthetic): step {step_syn}   PPL {ppl_syn:.2f}"  if ppl_syn  else "  Synthetic: not found")
print()

if ppl_orig is not None and ppl_syn is not None:
    ppl_diff = ppl_syn - ppl_orig
    if ppl_diff <= 3.0:
        USE_DIR = 'out-t3-synthetic'
        print(f"✓ Using SYNTHETIC checkpoint")
        print(f"  PPL diff: {ppl_diff:+.2f} (within ±3 threshold)")
        print(f"  Qwen quality will be significantly better")
    else:
        USE_DIR = 'out-t3-best'
        print(f"⚠ Using ORIGINAL checkpoint")
        print(f"  Synthetic PPL is {ppl_diff:.2f} pts worse — too risky for 15M marks")
        print(f"  PPL component is too important to sacrifice")
elif ppl_syn is not None:
    USE_DIR = 'out-t3-synthetic'
    print("Using synthetic (original not found)")
else:
    USE_DIR = 'out-t3-best'
    print("Using original (synthetic not found)")

print()
print(f"✓ HuggingFace upload will use: {USE_DIR}")
print()

# Copy sample_params.json to selected dir if not present
import shutil
sp_src = f'{USE_DIR}/sample_params.json'
if not os.path.exists(sp_src):
    shutil.copy('out-t3-best/sample_params.json', sp_src)
    print(f"✓ Copied sample_params.json to {USE_DIR}/")
"""


def new_code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": src_lines(source),
    }


def main() -> None:
    nb = json.loads(NB_PATH.read_text(encoding="utf-8"))
    cells = nb["cells"]
    joined = lambda: "".join("".join(c.get("source", [])) for c in cells)

    t3_idx = None
    for i, c in enumerate(cells):
        if MARKER_T3 in "".join(c.get("source", [])):
            t3_idx = i
            break
    if t3_idx is None:
        raise SystemExit(f"Could not find T3 cell with {MARKER_T3!r}")

    if "synthetic_stories_gptoss120b.json" not in joined():
        cells.insert(t3_idx, new_code_cell(CELL_SYN_PREP))
        t3_idx += 1

    if "T3_SYN_CONFIG" not in joined():
        cells.insert(t3_idx + 1, new_code_cell(CELL_T3_SYN))

    hf_idx = None
    for i, c in enumerate(cells):
        text = "".join(c.get("source", []))
        if "§3.4 HuggingFace" in text and "SUBMIT_DIR" in text and "T3_DIR" in text:
            hf_idx = i
            break
    if hf_idx is None:
        raise SystemExit("Could not find HuggingFace upload cell (§3.4)")

    if "Checkpoint Comparison" not in joined():
        cells.insert(hf_idx, new_code_cell(CELL_COMPARE))

    for c in cells:
        text = "".join(c.get("source", []))
        if "§3.4 HuggingFace" not in text or "T3_DIR" not in text:
            continue
        new_src = []
        for line in c["source"]:
            if line.strip() == "T3_DIR     = 'out-t3-best'":
                new_src.append(
                    "# USE_DIR set by comparison cell above; default to out-t3-best\n"
                )
                new_src.append(
                    "T3_DIR = USE_DIR if 'USE_DIR' in dir() else 'out-t3-best'\n"
                )
            else:
                new_src.append(line)
        c["source"] = new_src
        break

    old_t4 = (
        'print(f"\\n  ── Stage 2: Plain ROCStories fine-tune ───────────────────────────────")\n'
        'print(f"  Dataset  : data/rocstories_plain/")\n'
        'print(f"  Config   : {T4_S2_CONFIG}")\n'
        'print(f"  Out dir  : {T4_S2_OUT_DIR}")\n'
        'print(f"  Init     : resume (from Stage 1 best checkpoint)")\n'
        'print(f"  Steps    : 32,000")\n'
        'print(f"  ETA      : ~2.5 hrs on A100  (plain ROCStories; see train_t4_finetune.py)\\n")\n'
        "\n"
        "rc2 = run_streaming(\n"
    )
    new_t4 = (
        'print(f"\\n  ── Stage 2: Synthetic ROCStories fine-tune ───────────────────────────────")\n'
        'print(f"  Dataset  : data/rocstories_synthetic/  (~22.4M tokens, gpt-oss-120B KD)")\n'
        'print(f"  Config   : config/train_t4_finetune.py")\n'
        'print(f"  Out dir  : out-t4-arena")\n'
        'print(f"  Init     : resume (from Stage 1 best — step 25K)")\n'
        'print(f"  Steps    : 30,000  (25K Stage1 + 5K fine-tune = 5K new steps)")\n'
        'print(f"  ETA      : ~35 min on A100")\n'
        "\n"
        "# Verify synthetic dataset exists before starting\n"
        "if not os.path.exists('data/rocstories_synthetic/train.bin'):\n"
        '    print("⚠  data/rocstories_synthetic/train.bin not found!")\n'
        '    print("   Run §2.5 cell first to build the synthetic dataset.")\n'
        '    print("   Stopping — do not proceed without synthetic data.")\n'
        "    raise SystemExit(1)\n"
        'print("✓ Synthetic dataset verified")\n'
        "print()\n"
        "\n"
        "rc2 = run_streaming(\n"
    )

    for c in cells:
        src = c.get("source", [])
        full = "".join(src)
        if "T4_S2_CONFIG = 'config/train_t4_finetune.py'" in full and old_t4 in full:
            full = full.replace(old_t4, new_t4)
            c["source"] = src_lines(full)
            break

    for c in cells:
        full = "".join(c.get("source", []))
        if "§5 — FINAL SUMMARY" not in full or "ALL_RUNS" not in full:
            continue
        full = full.replace(
            "    ('out-t3-best',       'T3: Best Submission',   '#D85A30', True,  True,  True,  True ),\n",
            "    ('out-t3-best',       'T3 (orig): Best',       '#D85A30', True,  True,  True,  True ),\n"
            "    ('out-t3-synthetic',  'T3 (synth): gpt-oss KD', '#E67E22', True,  True,  True,  True ),\n",
        )
        full = full.replace(
            "    ('out-t4-arena',      'T4: Arena (124M)',        '#0F6E56', True,  True,  True,  True ),\n",
            "    ('out-t4-arena',      'T4: Arena (Stage 2: gpt-oss-120B synthetic)', '#0F6E56', True,  True,  True,  True ),\n",
        )
        c["source"] = src_lines(full)
        break

    NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print("Patched", NB_PATH)


if __name__ == "__main__":
    main()
